---
  - name: Instalação do pacotes 
    apt:
      pkg:
      - mysql-server
      - mysql-client
      - python3-mysqldb
      - libmysqlclient-dev
      state: present
      update_cache: yes

  - name : criando usuario wpuser
    mysql_user:
        name: "wpuser"
        password: "Wp@12345"
        priv: '*.*:ALL'
        host: "%"
        state: present   
  
  - name : Criando database wordpress
    mysql_db:
        name: "wordpress"
        state: present 